baseURL = "https://xxlsonnenschirm.github.io/xxlsonnenschirm/"
language = "de-CH"
title = "XXL Sonnenschirm"
enableRobotsTXT = true
theme = "terrassa"

[params.contact]
    email = "info@xxlsonnenschirm.ch"
    phone = "079 365 14 44"
    skype = ""
    address = "6405 Immensee"